from request_api import request_poloniex
from request_api import request_binance
from request_api import request_top
from request_api import request_marketcap
from request_api import request_btc
from request_api import request_bittrex
from request_api import request_cryptopia
from request_api import request_bitfinex
from request_api import request_all
from request_api import request_whale
